"""
Authority Notification Workflow
--------------------------------
M17.4 controlled notification workflow.

Connects an exported investigative alert report to the
notification service.

This module:
- validates the alert report,
- prepares a controlled notification,
- uses configured recipients,
- records every notification attempt,
- supports offline simulation,
- never claims guaranteed delivery.
"""

from __future__ import annotations

import json
from pathlib import Path

from src.monitoring.notification_service import (
    send_local_test_notification,
)


ROOT = Path(__file__).resolve().parents[2]

EXPORT_DIR = (
    ROOT
    / "reports"
    / "authority"
    / "exports"
)


def load_authority_report(txid: str) -> dict:
    """Load an existing controlled authority report."""
    path = EXPORT_DIR / f"authority_alert_{txid}.json"

    if not path.exists():
        raise FileNotFoundError(
            f"Authority report not found: {path}"
        )

    return json.loads(
        path.read_text(encoding="utf-8")
    )


def validate_authority_report(report: dict) -> None:
    """Validate minimum safeguards before notification."""
    required = {
        "report_type",
        "generated_at_utc",
        "txid",
        "investigative_status",
        "alert",
        "risk_evidence",
        "methodology_note",
        "limitations",
    }

    missing = required - set(report.keys())

    if missing:
        raise ValueError(
            f"Authority report missing fields: {sorted(missing)}"
        )

    if report["report_type"] != "controlled_investigative_alert":
        raise ValueError(
            "Invalid authority report type."
        )

    status = report["investigative_status"]

    protected_claims = [
        "identity_established",
        "ownership_established",
        "illicit_activity_established",
        "guilt_established",
    ]

    for field in protected_claims:
        if status.get(field) is not False:
            raise ValueError(
                f"Unsafe investigative claim detected: {field}"
            )


def build_notification_content(
    report: dict,
) -> tuple[str, str]:
    """Build a concise notification from validated evidence."""
    txid = str(report["txid"])

    alert = report.get("alert", {})

    priority = alert.get(
        "alert_priority",
        "UNKNOWN",
    )

    risk = alert.get(
        "risk_score",
        "UNKNOWN",
    )

    risk_level = alert.get(
        "risk_level",
        "UNKNOWN",
    )

    alert_status = alert.get(
        "alert_status",
        "UNKNOWN",
    )

    subject = (
        f"Bitcoin Investigative Alert | "
        f"TXID {txid} | Priority {priority}"
    )

    message = (
        "A Bitcoin transaction has been identified for "
        "investigative prioritization.\n\n"
        f"TXID: {txid}\n"
        f"Priority: {priority}\n"
        f"Risk Level: {risk_level}\n"
        f"Risk Score: {risk}\n"
        f"Alert Status: {alert_status}\n\n"
        "This notification contains investigative indicators "
        "generated by the monitoring system. It does not "
        "establish identity, ownership, illicit activity, "
        "or guilt. Independent investigative verification "
        "is required.\n\n"
        "Mode: offline controlled workflow."
    )

    return subject, message


def run_authority_notification_test(
    txid: str,
) -> list[dict]:
    """Run the controlled offline notification workflow."""
    report = load_authority_report(txid)

    validate_authority_report(report)

    subject, message = build_notification_content(report)

    return send_local_test_notification(
        subject=subject,
        message=message,
    )


if __name__ == "__main__":
    import sys

    if len(sys.argv) != 2:
        print(
            "Usage: python -B -m "
            "src.monitoring.authority_notification <TXID>"
        )
        raise SystemExit(2)

    records = run_authority_notification_test(
        sys.argv[1]
    )

    print(json.dumps(records, indent=2))